version: "3.5"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  alfa-data:
    driver: local

services:
  alfa-web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: core
    container_name: alfa-web
    ports:
      - 80:80
    environment:
      PHP_APP_HOST: "alfa-app:9000"
    volumes:
      - ./webroot/:/var/www/html/webroot
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      - frontend

  alfa-app:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: develop
    user: ${DEV_USER_ID:-www-data:www-data}
    container_name: alfa-app
    environment:
      - APP_NAME=app_alfa
      - STAGE_NAME=local
      - DEBUG=true
      - SERVER=false
      - SECURITY_SALT=rhq8PVFUFDEGCZG5E8DG860W7xXmaiX5H2HUmc1zog9OoDfGvC1V3GINvrTCpXU8
      - DB_LOG=true
      - DB_HOST=alfa-db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=local_alfa
      - DB_DATABASE_TEST=test_alfa
    volumes:
      - ./:/var/www/html
    networks:
      - frontend
      - backend

  alfa-db:
    image: mysql:5.7
    container_name: alfa-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=local_alfa
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql/etc-mysql.cnf:/etc/mysql/conf.d/etc-mysql.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - alfa-data:/var/lib/mysql
    networks:
      - backend
